theme: osuny
_merge: deep
params:
  plausible: rhu-talent.fr
  summary:
    position: hero
  search:
    active: true
  logo:
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  default:
    sitemap:
      ignore_children: true
  categories:
    index:
      layout: list
      options:
        image: false
  persons:
    contact_details:
      with_labels: false
  publications:
    filters:
      anr:
        - ANR-23-RHUS-0015
        - ANR-10-IAHU-0004
  laboratories:
    sitemap:
      ignore: true