theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  categories:
    index:
      layout: list
      options:
        image: false