theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  menu:
    primary:
      level_2:
        title:
          active: true